package Proyecto_Quimica.InterfazGrafica;

import javax.swing.JTextField;
import Proyecto_Quimica.Codigo_Principal.Controlador.LocalizacionController;
import javax.swing.table.DefaultTableModel;


public class FichaSalas extends javax.swing.JInternalFrame {
    
    private String nombreAlmacen;
    private int idLocalizacion;
    private LocalizacionController localizacionController;
    private final javax.swing.JTable tablaSalas;

    /**
     * Creates new form FichaUsuario
     */
        public FichaSalas(LocalizacionController localizacionController, int idLocalizacion, String nombreAlmacen, javax.swing.JTable tablaSalas) { 
            this.localizacionController = localizacionController;
            this.idLocalizacion = idLocalizacion;
            this.nombreAlmacen = nombreAlmacen;
            this.tablaSalas = tablaSalas;
            initComponents();
            // Para mostrar el nombre y apellido en las cajitas a editar de los usuarios
            mostrarPlaceholderSalas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tTexto = new javax.swing.JLabel();
        tNombre = new javax.swing.JLabel();
        iNombre = new javax.swing.JTextField();
        bBorrar = new javax.swing.JButton();
        bSalir = new javax.swing.JButton();
        bGuardar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Editar Sala");
        setMinimumSize(new java.awt.Dimension(512, 512));
        setVisible(false);

        tTexto.setText("Datos personales");

        tNombre.setText("Nombre:");

        iNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iNombreActionPerformed(evt);
            }
        });

        bBorrar.setText("Borrar");
        bBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBorrarActionPerformed(evt);
            }
        });

        bSalir.setText("Salir");
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });

        bGuardar.setText("Guardar");
        bGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tTexto))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(tNombre)
                        .addGap(11, 11, 11)
                        .addComponent(iNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(bBorrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 283, Short.MAX_VALUE)
                .addComponent(bGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bSalir)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(tTexto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tNombre)
                    .addComponent(iNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bBorrar)
                    .addComponent(bSalir)
                    .addComponent(bGuardar))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iNombreActionPerformed

    private void bBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBorrarActionPerformed
        localizacionController.eliminarUsuario(idLocalizacion);
        
        // Boramos la fila correspondiente de la JTable
        int filaSeleccionada = tablaSalas.getSelectedRow();
        ((DefaultTableModel) tablaSalas.getModel()).removeRow(filaSeleccionada);
        
    }//GEN-LAST:event_bBorrarActionPerformed

    private void bGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuardarActionPerformed
        String nuevoNombre = iNombre.getText();
        
        localizacionController.actualizarUsuario(idLocalizacion, nuevoNombre);
        
        // Actualizamos la fila correspondiente en la JTable
        int filaSeleccionada = tablaSalas.getSelectedRow();
        tablaSalas.setValueAt(nuevoNombre, filaSeleccionada, 1); 
        
    }//GEN-LAST:event_bGuardarActionPerformed

    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        // Cerramos la ventana de la ficha de usuario
        dispose();
    }//GEN-LAST:event_bSalirActionPerformed

    private void mostrarPlaceholderSalas() {
        iNombre.setText(nombreAlmacen);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBorrar;
    private javax.swing.JButton bGuardar;
    private javax.swing.JButton bSalir;
    private javax.swing.JTextField iNombre;
    private javax.swing.JLabel tNombre;
    private javax.swing.JLabel tTexto;
    // End of variables declaration//GEN-END:variables
}
