/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Proyecto_Quimica.InterfazGrafica;

import javax.swing.JTextField;
import Proyecto_Quimica.Codigo_Principal.Controlador.ProductoController;
import Proyecto_Quimica.Codigo_Principal.Controlador.UbicacionController;
import Proyecto_Quimica.Modelos.Producto;
import Proyecto_Quimica.Modelos.Ubicacion;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class FichaProductos extends javax.swing.JInternalFrame {

    private String nombre;
    private int idProducto;
    private String tipoProducto;
    private String nombreUbicacion;
    private int cantidad;
    private int stockMinimo;
    private Ubicacion ubiSeleccionada;
    private ProductoController productoController;
    private UbicacionController ubicacionController;
    List<Ubicacion> listaUbiNombres;
    private final javax.swing.JTable tablaProductos;
    
    public FichaProductos(ProductoController productoController, UbicacionController ubicacionController, int idProducto, String nombre, 
            String tipoProducto, String nombreUbicacion, int cantidad, int stockMinimo, javax.swing.JTable tablaProductos) {
        this.productoController = productoController;
        this.ubicacionController = ubicacionController;
        this.nombre = nombre;
        this.idProducto = idProducto;
        this.tipoProducto = tipoProducto;
        this.nombreUbicacion = nombreUbicacion;
        this.cantidad = cantidad;
        this.stockMinimo = stockMinimo;
        this.tablaProductos = tablaProductos;
        initComponents();
        //Para mostrar el nombre y apellido en las cajitas a editar de los usuarios
        rellenarUbicaciones();
        mostrarPlaceholderProductos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tTexto = new java.awt.Label();
        tNombre = new java.awt.Label();
        tNombre1 = new java.awt.Label();
        tUbicacion = new java.awt.Label();
        tCantidad = new java.awt.Label();
        tStockMin = new java.awt.Label();
        bBorrar = new java.awt.Button();
        bGuardar = new java.awt.Button();
        bSalir = new java.awt.Button();
        iNombre = new javax.swing.JTextField();
        iTipoProd = new javax.swing.JTextField();
        iCantidad = new javax.swing.JTextField();
        iStockMin = new javax.swing.JTextField();
        sUbiNombre = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        tTexto.setText("Datos Producto");

        tNombre.setText("Nombre:");

        tNombre1.setText("Tipo Producto:");

        tUbicacion.setText("Ubicación:");

        tCantidad.setText("Cantidad:");

        tStockMin.setText("Stock Mínimo:");

        bBorrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bBorrar.setLabel("Borrar");
        bBorrar.setName(""); // NOI18N
        bBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBorrarActionPerformed(evt);
            }
        });

        bGuardar.setLabel("Guardar");
        bGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuardarActionPerformed(evt);
            }
        });

        bSalir.setLabel("Salir");
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });

        iNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iNombreActionPerformed(evt);
            }
        });

        iTipoProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iTipoProdActionPerformed(evt);
            }
        });

        iCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iCantidadActionPerformed(evt);
            }
        });

        iStockMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iStockMinActionPerformed(evt);
            }
        });

        sUbiNombre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        sUbiNombre.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                sUbiNombreItemStateChanged(evt);
            }
        });
        sUbiNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                sUbiNombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                sUbiNombreFocusLost(evt);
            }
        });
        sUbiNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sUbiNombreMouseClicked(evt);
            }
        });
        sUbiNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sUbiNombreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tStockMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(iNombre)
                                    .addComponent(iTipoProd)
                                    .addComponent(iCantidad)
                                    .addComponent(iStockMin)
                                    .addComponent(sUbiNombre, 0, 230, Short.MAX_VALUE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(iNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addComponent(tNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(iTipoProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addComponent(tUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(sUbiNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(tStockMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(iStockMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBorrarActionPerformed
        productoController.eliminarProducto(idProducto);
        
        //Borramos la fila correspondiente de la JTable
        int filaSeleccionada = tablaProductos.getSelectedRow();
        ((DefaultTableModel) tablaProductos.getModel()).removeRow(filaSeleccionada);
    }//GEN-LAST:event_bBorrarActionPerformed

    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        // Cerramos la ventana de la ficha usuario
        dispose();
    }//GEN-LAST:event_bSalirActionPerformed

    private void bGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuardarActionPerformed
        String nuevoNombre = iNombre.getText();
        int nuevaUbicacion = ubiSeleccionada.getIdUbicacion();
        
        try {
            int nuevaCantidad = Integer.parseInt(iCantidad.getText());
            int nuevoMinStock = Integer.parseInt(iStockMin.getText());
            
            productoController.actualizarProducto(idProducto, nuevoNombre, nuevaUbicacion, nuevaCantidad, nuevoMinStock);
            
            //Actualizamos la fila correspondiente en la JTable
            int filaSeleccionada = tablaProductos.getSelectedRow();
            tablaProductos.setValueAt(nuevoNombre, filaSeleccionada, 1);
            tablaProductos.setValueAt(ubiSeleccionada.getNombre(), filaSeleccionada, 3);
            tablaProductos.setValueAt(nuevaCantidad, filaSeleccionada, 4);
            tablaProductos.setValueAt(nuevoMinStock, filaSeleccionada, 5);    
        }catch (Exception e){
            //Añadir JDialog popup
            System.out.println("Valores no validos en el formulario: " + e.getMessage());
        }
    }//GEN-LAST:event_bGuardarActionPerformed

    private void iNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iNombreActionPerformed

    private void iCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iCantidadActionPerformed

    private void iStockMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iStockMinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iStockMinActionPerformed

    private void iTipoProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iTipoProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iTipoProdActionPerformed

    private void sUbiNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sUbiNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sUbiNombreActionPerformed

    private void sUbiNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sUbiNombreFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_sUbiNombreFocusGained

    private void sUbiNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sUbiNombreFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_sUbiNombreFocusLost

    private void sUbiNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sUbiNombreMouseClicked
        sUbiNombre.showPopup();
    }//GEN-LAST:event_sUbiNombreMouseClicked

    private void sUbiNombreItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_sUbiNombreItemStateChanged
        
        int ubiTmp = sUbiNombre.getSelectedIndex();
        
        if(ubiTmp < listaUbiNombres.size()){
            ubiSeleccionada = listaUbiNombres.get(ubiTmp);
        }
    }//GEN-LAST:event_sUbiNombreItemStateChanged

    private void mostrarPlaceholderProductos() {
        iNombre.setText(nombre);
        iTipoProd.setText(tipoProducto);
        sUbiNombre.setSelectedItem(nombreUbicacion);
        iCantidad.setText(String.valueOf(cantidad));
        iStockMin.setText(String.valueOf(stockMinimo));
    }
    
    //metodo para rellenar el ComboBox sUbiName con los distintos nombre de las ubicaciones
    private void rellenarUbicaciones(){
        
        listaUbiNombres = ubicacionController.getUbicaciones();
        
        for (Ubicacion ubi: listaUbiNombres) {
            sUbiNombre.addItem(ubi.getNombre());
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button bBorrar;
    private java.awt.Button bGuardar;
    private java.awt.Button bSalir;
    private javax.swing.JTextField iCantidad;
    private javax.swing.JTextField iNombre;
    private javax.swing.JTextField iStockMin;
    private javax.swing.JTextField iTipoProd;
    private javax.swing.JComboBox<String> sUbiNombre;
    private java.awt.Label tCantidad;
    private java.awt.Label tNombre;
    private java.awt.Label tNombre1;
    private java.awt.Label tStockMin;
    private java.awt.Label tTexto;
    private java.awt.Label tUbicacion;
    // End of variables declaration//GEN-END:variables
}
