/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Proyecto_Quimica.InterfazGrafica;

import Proyecto_Quimica.Codigo_Principal.Controlador.ProductoController;
import Proyecto_Quimica.Codigo_Principal.Controlador.UbicacionController;
import Proyecto_Quimica.Modelos.Producto;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;



public class ListaProducto extends javax.swing.JInternalFrame {

    private ProductoController productoController;
    private UbicacionController ubicacionController;
    List<Producto> listaProductos;
    
    public ListaProducto(ProductoController productoController, UbicacionController ubicacionController) {
        this.productoController = productoController;
        this.ubicacionController = ubicacionController;
        initComponents();
        listaProductos = productoController.getProductos();
        mostrarDatos(listaProductos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaProductos = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        TablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nombre Producto", "Tipo Producto", "Ubicación", "Cantidad", "Stock Mínimo"
            }
        ));
        TablaProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaProductos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TablaProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaProductosMouseClicked
        int filaClickada = TablaProductos.getSelectedRow();
        //Verificamos que se haya seleccionado una fila
        if(filaClickada != -1) {
            Producto producto = listaProductos.get(filaClickada);
            //Abrir una nueva ventana de edicion de usuario
            FichaProductos fichaProductos = new FichaProductos(productoController, ubicacionController, producto.getIdProducto(),
            producto.getNombre(), producto.getTipoToString(), producto.getNombreUbicacion(), producto.getCantidad(), producto.getStockMinimo(), TablaProductos);
            this.add(fichaProductos);
            fichaProductos.show();
        }
    }//GEN-LAST:event_TablaProductosMouseClicked

    public JTable getTablaProductos(){
        return TablaProductos;
    }
    
    public void mostrarDatos(List<Producto> listaProductos) {
        //La JTable que he añadido en el diseño de la vista tomará la estructura
        //del DefaultModel, ya que no tenemos una estructura definida para la 
        //tabla.
        //https://www.thoughtco.com/defaulttablemodel-overview-2033890
        //https://es.stackoverflow.com/questions/23295/asignar-un-defaulttablemodel-a-un-jtable-mvc
        //y con view.getTablaUsuarios() cogemos el JTable de la vista y con el
        //.getModel(), segun la definicion: Returns tha TableModel that provides the data displayed by this JTable.
        DefaultTableModel model = (DefaultTableModel) this.getTablaProductos().getModel();
        //Limpiar la tabla antes de cargar nuevos datos
        model.setRowCount(0);
        for (Producto prod : listaProductos) {
            Object[] fila = {prod.getIdProducto(), prod.getNombre(), prod.getTipoToString(), prod.getNombreUbicacion(), prod.getCantidad(), prod.getStockMinimo()};
            model.addRow(fila);
                
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaProductos;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
