/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Proyecto_Quimica.InterfazGrafica;

import Proyecto_Quimica.Codigo_Principal.Controlador.UbicacionController;
import Proyecto_Quimica.Modelos.Ubicacion;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DAW
 */
public class ListaUbicaciones extends javax.swing.JInternalFrame {

    private UbicacionController ubicacionController;
    List<Ubicacion> listaUbicaciones;
    
    public ListaUbicaciones(UbicacionController ubicacionController) {
        this.ubicacionController = ubicacionController;
        initComponents();
        listaUbicaciones = ubicacionController.getUbicaciones();
        mostrarDatos(listaUbicaciones);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaUbicaciones = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        TablaUbicaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Código", "Nombre Ubicación"
            }
        ));
        TablaUbicaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaUbicacionesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaUbicaciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TablaUbicacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaUbicacionesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TablaUbicacionesMouseClicked

    public JTable getTablaUsuarios(){
        return TablaUbicaciones;
    }
    
    public void mostrarDatos(List<Ubicacion> listaUbicaciones){
        //La JTable que he añadido en el diseño de la vista tomará la estructura
        //del DefaultModel, ya que no tenemos una estructura definida para la 
        //tabla.
        //https://www.thoughtco.com/defaulttablemodel-overview-2033890
        //https://es.stackoverflow.com/questions/23295/asignar-un-defaulttablemodel-a-un-jtable-mvc
        //y con view.getTablaUsuarios() cogemos el JTable de la vista y con el
        //.getModel(), segun la definicion: Returns tha TableModel that provides the data displayed by this JTable.
        DefaultTableModel model = (DefaultTableModel) this.getTablaUsuarios().getModel();
        //Limpiar la tabla antes de cargar nuevos datos
        model.setRowCount(0);
        for (Ubicacion ubi : listaUbicaciones) {
            Object[] fila = {ubi.getIdUbicacion(), ubi.getNombre()};
            model.addRow(fila);
                
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaUbicaciones;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
