/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Proyecto_Quimica.InterfazGrafica;


public class Sobre extends javax.swing.JInternalFrame {

    /**
     * Creates new form Sobre
     */
    public Sobre() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Nuestro proyecto de programación y base de datos, desarrollado por dos alumnos del primer año del \nciclo de Desarrollo de Aplicaciones Web (DAW) en el I.E.S. Zaidín Vergeles, se presenta como una \nsolución innovadora para el manejo de reactivos, materiales químicos y productos auxiliares en \nlaboratorios institucionales. Daniel Fontalva y Tomás Robertson, con su pasión por la programación y el \ndiseño de sistemas eficientes, han creado una aplicación informática que revoluciona la forma en que se \ngestiona el inventario en entornos de investigación científica.  \n\nEsta iniciativa, nacida en el contexto del aprendizaje en el ámbito de la programación, destaca por su \nenfoque práctico y orientado a las necesidades reales de los usuarios. La aplicación desarrollada por \nFontalva y Robertson ofrece una interfaz amigable y funcionalidades personalizables que permiten a \nlos usuarios, incluso aquellos menos familiarizados con la tecnología, gestionar de manera eficiente los \nrecursos del laboratorio, mejorando así su productividad y seguridad en el manejo de sustancias \nquímicas.  \n\nEl compromiso de Fontalva y Robertson con la excelencia en el desarrollo de software se refleja en cada \naspecto de esta solución, desde la robustez de la base de datos hasta la usabilidad del interfaz de \nusuario. Su proyecto no solo simplifica la gestión de inventarios en entornos científicos complejos, sino \nque también demuestra el potencial transformador de la educación técnica y la aplicación práctica de \nlos conocimientos adquiridos en el aula.");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 606, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 323, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
